debug: true

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  stream : logs

app_name: ESLogIndexer

max_records: 1000

elastic_search:
  host: 5ef1fe1be448f837d91a38960abf6c0a.us-east-1.aws.found.io
  cluster: 5ef1fe1be448f837d91a38960abf6c0a
  api_key: 81222e33460b425be887e3fb8d0521b6
  http_port: 9243
  tcp_port: 9343
  nodes_sampler_interval: 30s
  ping_timeout: 30s
  index_prefix: sense-logs-
  max_bulk_actions: 500
  max_bulk_size_mb: 1000
  bulk_concurrent_requests: 2
  bulk_await_close_seconds: 15

logging:
  level: INFO
  loggers:
    com.hello.suripu: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/logsindexer/logsindexer.log
      archivedLogFilenamePattern: /var/log/logsindexer/logsindexer-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: logsindexer-prod
      # timezone: UTC
      # facility: USER
      # sendLocalName: true
