debug: false

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  stream : logs

app_name: ESLogIndexerProd

max_records: 200

elastic_search:
  host: 5ef1fe1be448f837d91a38960abf6c0a.us-east-1.aws.found.io
  cluster: 5ef1fe1be448f837d91a38960abf6c0a
  api_key: r3adk76np2q256hk41
  http_port: 9243
  tcp_port: 9343
  nodes_sampler_interval: 30s
  ping_timeout: 30s
  index_prefix: sense-logs-
  fallback_index: sense-logs-fallback
  fw_crash_index: sense-logs-fw-crash
  internal_test_index: sense-logs-internal-test
  max_bulk_actions: 50
  max_bulk_size_mb: 200
  bulk_concurrent_requests: 2
  bulk_await_close_seconds: 15


metrics_enabled: true

graphite:
  host: carbon.hostedgraphite.com
  api_key: 7509c0ff-4db5-4cae-91ee-6e78ff13b336
  reporting_interval_in_seconds: 30
  include_metrics:
    - com.hello

logging:
  level: INFO
  loggers:
    com.hello.suripu: DEBUG
  appenders:
    - type: file
      threshold: DEBUG
      currentLogFilename: /var/log/logsindexer/logsindexer.log
      archivedLogFilenamePattern: /var/log/logsindexer/logsindexer-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
    - type: papertrail
      host: logs2.papertrailapp.com
      port: 11366
      ident: logsindexer-prod
      # timezone: UTC
      # facility: USER
      # sendLocalName: true

redis:
  host: stats.xoe7je.0001.use1.cache.amazonaws.com
  port: 6379