debug: true

kinesis:
  endpoint : https://kinesis.us-east-1.amazonaws.com
  stream : logs

app_name: ESLogIndexer

max_records: 200

elastic_search:
  host: 5ef1fe1be448f837d91a38960abf6c0a.us-east-1.aws.found.io
  cluster: 5ef1fe1be448f837d91a38960abf6c0a
  api_key: 81222e33460b425be887e3fb8d0521b6
  http_port: 9243
  tcp_port: 9343
  nodes_sampler_interval: 30s
  ping_timeout: 30s
  index_prefix: sense-logs-
  max_bulk_actions: 50
  max_bulk_size_mb: 300


